version: '3.8'

services:
  web:
    build: .
    container_name: php-app
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    env_file:
      - ./build/env/development.env

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    env_file:
      - ./build/env/development.env
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./crear_base.sql:/docker-entrypoint-initdb.d/crear_base.sql

volumes:
  db_data:
